#!/bin/bash

# Quick Start Guide for 3Data Cleaner & Value Type Predictor

echo "🚀 3Data Cleaner & Value Type Predictor"
echo "=========================================="
echo ""
echo "✅ Prerequisites:"
echo "   - Python 3.8 or higher installed"
echo "   - pip package manager"
echo ""
echo "📦 Installation Steps:"
echo ""
echo "1. Navigate to project directory:"
echo "   cd Pandas-and-numpy-ML-Project.worktrees/agents-three-data-cleaner-prediction"
echo ""
echo "2. Install dependencies:"
echo "   pip install -r requirements.txt"
echo ""
echo "3. Run the Flask application:"
echo "   python app.py"
echo ""
echo "4. Open your browser and visit:"
echo "   http://localhost:5000"
echo ""
echo "📋 Features Available:"
echo "   ✨ Tab 1: Type Detection - Detect if input is number, text, date, etc."
echo "   💰 Tab 2: Price Prediction - Predict car prices from features"
echo "   📊 Tab 3: Batch Analysis - Analyze multiple values at once"
echo ""
echo "🔧 To stop the server: Press Ctrl+C"
echo ""
echo "📝 For more info, see README.md"
